"""empty message

Revision ID: c389419ce9a4
Revises: 1e3070aebe85
Create Date: 2025-04-26 13:38:59.688006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c389419ce9a4'
down_revision: Union[str, None] = '1e3070aebe85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'dictionary_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('words_dictionary_id_fkey', 'words', type_='foreignkey')
    op.create_foreign_key(None, 'words', 'dictionaries', ['dictionary_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.create_foreign_key('words_dictionary_id_fkey', 'words', 'dictionaries', ['dictionary_id'], ['id'])
    op.alter_column('words', 'dictionary_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
